django_app/apps/accounts/urls.py
from django.urls import path
from apps.accounts.forms.login_form import LoginForm
from apps.accounts.views.register_view import RegisterView
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    
    path('login/', LoginView.as_view(
        template_name='registration/login.html', 
        redirect_authenticated_user=True, 
        authentication_form=LoginForm
    ), name='login'),
    
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

django_app/apps/home/urls.py
from django.urls import path
from apps.home.views import HomeView, AboutView
from django.views.generic.base import RedirectView

app_name = "home"

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('', RedirectView.as_view(pattern_name='home:home', permanent=False)),
]

django_app/apps/mailbot/urls.py
from django.urls import path
from apps.mailbot.views.email_input_view import EmailInputView
from apps.mailbot.views.email_detail_view import EmailDetailView
from apps.mailbot.views.email_list_view import EmailListView

app_name = 'mailbot'

urlpatterns = [
    path('input/', EmailInputView.as_view(), name='input'),
    path('<int:pk>/', EmailDetailView.as_view(), name='detail'),
    path('', EmailListView.as_view(), name='list'),
]

django_app/core/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path("mail/", include("apps.mailbot.urls", namespace="mailbot")),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = "apps.home.views.custom_404_view"

django_app/templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  
  {% bootstrap_css %}
  
  <link rel="stylesheet" href={% static "css/style.css" %}>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  {% block styles %}{% endblock %}

</head>

<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-dark text-light">
      <div class="modal-header border-0">
        <h5 class="modal-title" id="logoutModalLabel">Confirmação</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Fechar"></button>
      </div>
      <div class="modal-body">
        Tem certeza que deseja sair?
      </div>
      <div class="modal-footer border-0">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <form method="post" action="{% url 'accounts:logout' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Sair</button>
        </form>
      </div>
    </div>
  </div>
</div>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2">
      <div class="container">

        <a class="navbar-brand d-flex align-items-center" href={% url "home:home" %}>
          <img src={% static "img/logo.png" %} alt="Logo" class="nav__logo me-2">
          <span class="d-flex flex-column text-white fw-bold fs-4 lh-1">
            <span class="text-danger">No</span>
            <span>Scaries</span>
          </span>
        </a>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarContent"
          aria-controls="navbarContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end mt-1" id="navbarContent">
          <ul class="navbar-nav align-items-center gap-2">
            <li class="nav-item">
              <a class="nav-link fw-bold menu-link" href="{% url 'home:about' %}">Sobre</a>
            </li>

            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link fw-bold menu-link" href="{% url 'mailbot:input' %}">Verificar E-mail</a>
              </li>

              <li class="nav-item">
                <a class="nav-link fw-bold menu-link" href="{% url 'mailbot:list' %}">Histórico</a>
              </li>

              <li class="nav-item">
                <a class="nav-link fw-bold menu-link" href="#" data-bs-toggle="modal" data-bs-target="#logoutModal">
                  Sair
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link fw-bold menu-link" href="{% url 'accounts:login' %}">Login</a>
              </li>

              <li class="nav-item">
                <a class="nav-link fw-bold menu-link" href="{% url 'accounts:register' %}">Registrar</a>
              </li>
            {% endif %}
            
          </ul>
        </div>

      </div>
    </nav>
  </header>

  <main>
    {% block content %}{% endblock %}
  </main>

  <footer class="bg-dark text-light py-2 border-top border-secondary mt-auto">
    <div class="container d-flex flex-column flex-md-row justify-content-between align-items-center">
      
      <span class="small text-muted mb-2 mb-md-0">
        &copy; 2024 No Scaries. Todos os direitos reservados.
      </span>

      <div>

        <a href="https://www.linkedin.com/in/fernando-luiz-farias-fontes/" target="_blank" rel="noopener" class="text-light fs-4 me-3">
          <i class="fab fa-linkedin footer__icons"></i>
        </a>

        <a href="https://github.com/Nando2003" target="_blank" rel="noopener" class="text-light fs-4 ">
          <i class="fab fa-github footer__icons"></i>
        </a>

      </div>

    </div>
  </footer>

  {% bootstrap_javascript %}
  {% block scripts %}{% endblock %}

  <div id="loadingOverlay" style="
      display: none;
      position: fixed;
      z-index: 9999;
      top: 0; left: 0; right: 0; bottom: 0;
      background: rgba(0,0,0,0.7);
      align-items: center;
      justify-content: center;
  ">
    <div>
      <div class="spinner-border text-danger" style="width: 3rem; height: 3rem;" role="status">
        <span class="visually-hidden">Carregando...</span>
      </div>
    </div>
  </div>

</body>
</html>